apiVersion: v1
kind: Pod
metadata:
  name: nfs-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          # name must match the volume name below
          - name: nfs-vol
            mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: nfs-pvc001